openapi: 3.0.3
info:
  title: Vlaamse Overheids Vergunningen Databank
  description: API portal om vergunningen te beheren voor evenementen
  version: 1.0.0
  contact:
    name: VO Vergunningen Databank
    url: "https://www.vlaamse-overheid.be/"
    email: vergunningen@vlaamse-overheid.be
tags:
  - name: Vergunningen
servers:
  - url: "https://api-dev-vlaamse-overheid.be/v2"
    description: "DEV server"
paths:
  /vergunningen:
    post:
      operationId: postVergunningen
      security:
        - basicAuth: []
      tags:
        - Vergunningen
      description: |-
        Het aanmaken van een aanvraag voor een vergunning bij de Vlaamse Overheid
      requestBody:
        content:
          application/json:
            schema:
              required:
                - startEvenement
                - eindeEvenement
                - straat
                - nummer
                - stad
                - postcode
                - bestuurNr
                - bestuurNaam
                - bestuurPostcode
                - aanvragerEmail
                - aanvragerTelefoon
                - aanvragerRijksregisternr
                - aanvragerVoornaam
                - aanvragernaam
                - aanvragerGeboortedatum
                - aanvragerKBOnr
                - aanvragerMaatschappelijkeNaam
                - aanvragerVorm
              properties:
                startEvenement:
                  type: string
                eindeEvenement:
                  type: string
                straat:
                  type: string
                nummer:
                  type: string
                stad:
                  type: string
                postcode:
                  type: string
                bestuurNr:
                  type: string
                bestuurNaam:
                  type: string
                bestuurPostcode:
                  type: string
                aanvragerEmail:
                  type: string
                aanvragerTelefoon:
                  type: string
                aanvragerRijksregisternr:
                  type: string
                aanvragerVoornaam:
                  type: string
                aanvragerNaam:
                  type: string
                aanvragerGeboortedatum:
                  type: string
                aanvragerKBOnr:
                  type: string
                aanvragerMaatschappelijkeNaam:
                  type: string
                aanvragerVorm:
                  type: string
                ambtenaarEmail:
                  type: string
                ambtenaarTelefoon:
                  type: string
                ambtenaarRijksregisternr:
                  type: string
                ambtenaarVoornaam:
                  type: string
                ambtenaarNaam:
                  type: string
                ambtenaarGeboortedatum:
                  type: string

      responses:
        "200":
          description: Vergunning Aangemaakt
          content:
            application/json:
              schema:
                required:
                  - startEvenement
                  - eindeEvenement
                  - straat
                  - nummer
                  - stad
                  - postcode
                  - bestuurNr
                  - bestuurNaam
                  - bestuurPostcode
                  - resultaatBeslissing
                  - datumAanvraag
                  - datumBeslissing
                  - dossierNr
                  - aanvragerEmail
                  - aanvragerTelefoon
                  - aanvragerRijksregisternr
                  - aanvragerVoornaam
                  - aanvragernaam
                  - aanvragerGeboortedatum
                  - aanvragerKBOnr
                  - aanvragerMaatschappelijkeNaam
                  - aanvragerVorm
                  - ambtenaarEmail
                  - ambtenaarTelefoon
                  - ambtenaarVoornaam
                  - ambtenaarNaam
                  - ambtenaarRijksregisternr
                  - ambtenaarGeboortedatum
                properties:
                  startEvenement:
                    type: string
                  eindeEvenement:
                    type: string
                  straat:
                    type: string
                  nummer:
                    type: string
                  stad:
                    type: string
                  postcode:
                    type: string
                  bestuurNr:
                    type: string
                  bestuurNaam:
                    type: string
                  bestuurPostcode:
                    type: string
                  aanvragerEmail:
                    type: string
                  aanvragerTelefoon:
                    type: string
                  aanvragerRijksregisternr:
                    type: string
                  aanvragerVoornaam:
                    type: string
                  aanvragerNaam:
                    type: string
                  aanvragerGeboortedatum:
                    type: string
                  aanvragerKBOnr:
                    type: string
                  aanvragerMaatschappelijkeNaam:
                    type: string
                  aanvragerVorm:
                    type: string
                  ambtenaarEmail:
                    type: string
                  ambtenaarTelefoon:
                    type: string
                  ambtenaarRijksregisternr:
                    type: string
                  ambtenaarVoornaam:
                    type: string
                  ambtenaarNaam:
                    type: string
                  ambtenaarGeboortedatum:
                    type: string
  /vergunningen/{dossierNr}:
    get:
      operationId: getVergunningenDetails
      security:
        - basicAuth: []
      tags:
        - Vergunningen
      description: |-
        Details opvragen van een bepaalde vergunning
      parameters:
        - in: path
          name: dossierNr
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Vergunning
          content:
            application/json:
              schema:
                required:
                  - startEvenement
                  - eindeEvenement
                  - straat
                  - nummer
                  - stad
                  - postcode
                  - bestuurNr
                  - bestuurNaam
                  - bestuurPostcode
                  - resultaatBeslissing
                  - datumAanvraag
                  - datumBeslissing
                  - dossierNr
                  - aanvragerEmail
                  - aanvragerTelefoon
                  - aanvragerRijksregister
                  - aanvragerVoornaam
                  - aanvragernaam
                  - aanvragerGeboortedatum
                properties:
                  startEvenement:
                    type: string
                  eindeEvenement:
                    type: string
                  straat:
                    type: string
                  nummer:
                    type: string
                  stad:
                    type: string
                  postcode:
                    type: string
                  bestuurNr:
                    type: string
                  bestuurNaam:
                    type: string
                  bestuurPostcode:
                    type: string
                  aanvragerEmail:
                    type: string
                  aanvragerTelefoon:
                    type: string
                  aanvragerRijksregisternr:
                    type: string
                  aanvragerVoornaam:
                    type: string
                  aanvragerNaam:
                    type: string
                  aanvragerGeboortedatum:
                    type: string
                  aanvragerKBOnr:
                    type: string
                  aanvragerMaatschappelijkeNaam:
                    type: string
                  aanvragerVorm:
                    type: string
                  ambtenaarEmail:
                    type: string
                  ambtenaarTelefoon:
                    type: string
                  ambtenaarRijksregisternr:
                    type: string
                  ambtenaarVoornaam:
                    type: string
                  ambtenaarNaam:
                    type: string
                  ambtenaarGeboortedatum:
                    type: string